"""market_snapshot_table

Revision ID: 3e9fcf0f6d4e
Revises: 209bf6bdd659
Create Date: 2026-07-12 23:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9fcf0f6d4e'
down_revision: Union[str, Sequence[str], None] = '209bf6bdd659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('outcomes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('outcome_prices', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('volume_1w', sa.Float(), nullable=True),
    sa.Column('volume_1m', sa.Float(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('closed', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshot_market_id'), 'market_snapshot', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_snapshot_timestamp'), 'market_snapshot', ['timestamp'], unique=False)
    op.create_index('ix_market_snapshot_market_time', 'market_snapshot', ['market_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_snapshot_market_time', table_name='market_snapshot')
    op.drop_index(op.f('ix_market_snapshot_timestamp'), table_name='market_snapshot')
    op.drop_index(op.f('ix_market_snapshot_market_id'), table_name='market_snapshot')
    op.drop_table('market_snapshot')
    # ### end Alembic commands ###
